"""Bootstrap LiteLLM virtual keys (role -> model allowlist).

This script is meant to run inside docker-compose as a one-off container.
It will:
  1) wait for LiteLLM /health to be ready
  2) call /key/generate 3 times (intern/employee/admin)
  3) write keys to /keys/keys.env

NOTE: We intentionally do NOT require upstream API keys in this HW.
"""

import os
import time
import json
import requests

LITELLM_BASE_URL = os.getenv("LITELLM_BASE_URL", "http://litellm:4000").rstrip("/")
LITELLM_MASTER_KEY = os.getenv("LITELLM_MASTER_KEY", "master-key")
OUT_PATH = os.getenv("LITELLM_KEYS_FILE", "/keys/keys.env")

# Required allowlist (as per 指令.docx)
MODEL_OLM = os.getenv("OLM_MODEL_NAME", "allenai/olmOCR-2-7B-1025-FP8")
MODEL_LLM = os.getenv("LLM_MODEL_NAME", "/models/Qwen3-30B-A3B-Instruct-2507-FP8")
MODEL_VLM = os.getenv("VLM_MODEL_NAME", "gemma-3-27b-it")


import os, time, requests

LITELLM_URL = os.getenv("LITELLM_URL", "http://litellm:4000")
MASTER_KEY = os.getenv("LITELLM_MASTER_KEY", "")

def wait_ready(timeout=120):
    headers = {}
    # LiteLLM 用 Bearer master key
    if MASTER_KEY:
        headers["Authorization"] = f"Bearer {MASTER_KEY}"

    deadline = time.time() + timeout
    last_err = None
    while time.time() < deadline:
        try:
            # 用 /v1/models 當 ready check（比 /health 更穩）
            r = requests.get(f"{LITELLM_URL}/v1/models", headers=headers, timeout=3)
            if r.status_code == 200:
                return True
            last_err = f"{r.status_code} {r.text[:200]}"
        except Exception as e:
            last_err = str(e)
        time.sleep(2)
    raise RuntimeError(f"litellm_not_ready: {last_err}")


def gen_key(alias: str, models: list[str]) -> str:
    """Generate a virtual key with model allowlist.

    LiteLLM versions differ slightly in response shape; we handle common variants.
    """
    url = f"{LITELLM_BASE_URL}/key/generate"
    headers = {"Authorization": f"Bearer {LITELLM_MASTER_KEY}", "Content-Type": "application/json"}
    payload = {
        "key_alias": alias,
        "models": models,
        "metadata": {"role": alias, "source": "bootstrap"},
    }

    resp = requests.post(url, headers=headers, json=payload, timeout=30)
    if resp.status_code >= 400:
        raise RuntimeError(f"key_generate_failed:{resp.status_code}:{resp.text}")

    data = resp.json()
    # common fields
    for k in ("key", "token", "api_key"):
        if k in data and isinstance(data[k], str) and data[k].strip():
            return data[k].strip()
    # sometimes nested
    if isinstance(data.get("data"), dict):
        for k in ("key", "token", "api_key"):
            v = data["data"].get(k)
            if isinstance(v, str) and v.strip():
                return v.strip()

    raise RuntimeError(f"key_generate_bad_response:{json.dumps(data)[:200]}")


def main() -> None:
    wait_ready()

    intern_key = gen_key("intern", [MODEL_LLM])
    employee_key = gen_key("employee", [MODEL_LLM])
    admin_key = gen_key("admin", [MODEL_LLM, MODEL_VLM])

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/bootstrap_litellm_keys.py\n")
        f.write(f"LITELLM_KEY_INTERN={intern_key}\n")
        f.write(f"LITELLM_KEY_EMPLOYEE={employee_key}\n")
        f.write(f"LITELLM_KEY_ADMIN={admin_key}\n")

    print(f"[bootstrap] wrote keys to {OUT_PATH}")


if __name__ == "__main__":
    main()
