import os
import time
import requests, json
from fastapi import FastAPI, Depends, HTTPException, Response, Request
from fastapi.responses import JSONResponse
from typing import List
from redis import Redis

from gateway.app.auth import get_user_ctx, issue_token, UserCtx
from gateway.app.schemas import LoginReq, LoginResp, ToolCallReq, ChatReq, AgentRunReq
from gateway.app.registry import load_registry
from gateway.app.policy import is_allowed, ROLE_TO_SCOPES
from gateway.app.rate_limit import check_rate_limit
from gateway.app.audit import audit
from gateway.app.observability import CORRELATION_HEADER, new_correlation_id, error_envelope
from gateway.app.agent import ToolSpec, load_agent_visibility, filter_tools_for_role, build_langgraph_agent, _matches

REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
TIMEOUT = int(os.getenv("REQUEST_TIMEOUT", "60"))
MEMORY_TTL = int(os.getenv("MEMORY_TTL_SECONDS", "3600"))
MEMORY_MAX_TURNS = int(os.getenv("MEMORY_MAX_TURNS", "12"))  # last N lines kept (USER/ASSISTANT mixed)

# Lightweight profile memory (name recall) – works even when LLM upstream is down.
# Stored per (user_id, conversation_id) with TTL aligned to MEMORY_TTL.
import re

NAME_PATTERNS = [
    re.compile(r"我叫(?P<name>[\u4e00-\u9fffA-Za-z0-9_]{1,12})"),
    re.compile(r"我是(?P<name>[\u4e00-\u9fffA-Za-z0-9_]{1,12})"),
    re.compile(r"叫我(?P<name>[\u4e00-\u9fffA-Za-z0-9_]{1,12})"),
]

ASK_NAME_PATTERNS = [
    re.compile(r"我叫什麼"),
    re.compile(r"我名字是什麼"),
    re.compile(r"我的名字"),
]

# Simple cost / traffic controls
BUDGET_RPM = int(os.getenv("BUDGET_RPM", "120"))  # in addition to RATE_LIMIT_RPM; used for agent endpoints
BUDGET_DAILY_CHARS = int(os.getenv("BUDGET_DAILY_CHARS", "80000"))

# LiteLLM proxy (OpenAI-compatible)
LITELLM_BASE_URL = os.getenv("LITELLM_BASE_URL", "http://litellm:4000")
DEFAULT_MODEL = os.getenv("DEFAULT_MODEL", "").strip() or None
# When LiteLLM blocks, add this marker for easy verification
BLOCKED_HEADER_NAME = "x-blocked-by"
BLOCKED_HEADER_VALUE = "litellm"

# Optional: a shared env file written by scripts/bootstrap_litellm_keys.py
LITELLM_KEYS_FILE = os.getenv("LITELLM_KEYS_FILE", "/keys/keys.env")

app = FastAPI(title="API Gateway (MCP Aggregator)")
r = Redis.from_url(REDIS_URL, decode_responses=True)

servers = {s["name"]: s["base_url"] for s in load_registry()}

# Build LangGraph once (lazy import inside)
try:
    LG_AGENT = build_langgraph_agent()
except Exception:
    LG_AGENT = None


@app.middleware("http")
async def _correlation_mw(request: Request, call_next):
    cid = request.headers.get(CORRELATION_HEADER) or new_correlation_id()
    request.state.correlation_id = cid
    resp = await call_next(request)
    resp.headers[CORRELATION_HEADER] = cid
    # Minimal observability: ensure CID is grep-able in logs.
    # Keep this as a single line for easy parsing.
    try:
        print(f"CID={cid} method={request.method} path={request.url.path} status={resp.status_code}")
    except Exception:
        pass
    return resp


def _budget_key(user_id: str) -> str:
    # UTC day bucket
    day = time.strftime("%Y%m%d", time.gmtime())
    return f"budget:{user_id}:{day}"


def _consume_budget(rds: Redis, user_id: str, *, n_chars: int) -> bool:
    """Return True if allowed, False if exceeded."""
    key = _budget_key(user_id)
    used = rds.incrby(key, n_chars)
    # expire a bit after 24h to keep redis tidy
    rds.expire(key, 60 * 60 * 30)
    return used <= BUDGET_DAILY_CHARS


def _load_role_keys() -> dict[str, str]:
    """Load role->virtual key mapping.

    Priority:
      1) keys.env file generated by bootstrap container
      2) explicit env vars

    keys.env format:
      LITELLM_KEY_INTERN=...
      LITELLM_KEY_EMPLOYEE=...
      LITELLM_KEY_ADMIN=...
    """
    mapping: dict[str, str] = {}

    # 1) file
    try:
        if os.path.exists(LITELLM_KEYS_FILE):
            with open(LITELLM_KEYS_FILE, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    k, v = line.split("=", 1)
                    v = v.strip().strip('"')
                    if k == "LITELLM_KEY_INTERN":
                        mapping["intern"] = v
                    elif k == "LITELLM_KEY_EMPLOYEE":
                        mapping["employee"] = v
                    elif k == "LITELLM_KEY_ADMIN":
                        mapping["admin"] = v
    except Exception:
        # ignore file parsing errors; env fallback below
        pass

    # 2) env fallback
    mapping.setdefault("intern", os.getenv("LITELLM_KEY_INTERN", ""))
    mapping.setdefault("employee", os.getenv("LITELLM_KEY_EMPLOYEE", ""))
    mapping.setdefault("admin", os.getenv("LITELLM_KEY_ADMIN", ""))

    # drop empties
    return {k: v for k, v in mapping.items() if v}


def _litellm_chat_completion(*, virtual_key: str, model: str, message: str, history: list[str]) -> str:
    # Keep payload OpenAI-compatible.
    # Convert our Redis history lines to messages for better context (optional).
    messages = []
    # History is stored as strings like "USER: ..." and "ASSISTANT: ..." (lpush => newest first)
    # We received it as lrange(0,20) => newest..older; reverse to old..new
    for line in reversed(history):
        if line.startswith("USER: "):
            messages.append({"role": "user", "content": line[len("USER: "):]})
        elif line.startswith("ASSISTANT: "):
            messages.append({"role": "assistant", "content": line[len("ASSISTANT: "):]})

    # Add current user message at the end
    messages.append({"role": "user", "content": message})

    url = f"{LITELLM_BASE_URL.rstrip('/')}/v1/chat/completions"
    headers = {"Authorization": f"Bearer {virtual_key}", "Content-Type": "application/json"}
    payload = {"model": model, "messages": messages, "stream": False}

    resp = requests.post(url, headers=headers, json=payload, timeout=TIMEOUT)
    if resp.status_code >= 400:
        # Pass through a clean error message; caller will attach headers for identification.
        try:
            detail = resp.json()
        except Exception:
            detail = {"raw": resp.text}
        raise HTTPException(status_code=resp.status_code, detail={"blocked_by": "litellm", "litellm": detail})

    data = resp.json()
    # OpenAI-compatible response parsing
    try:
        return data["choices"][0]["message"]["content"]
    except Exception:
        raise HTTPException(502, "litellm_bad_response")


@app.post("/auth/login", response_model=LoginResp)
def login(req: LoginReq):
    scopes = ROLE_TO_SCOPES.get(req.role)
    if not scopes:
        raise HTTPException(400, "invalid_role")
    token = issue_token(req.user_id, req.role, scopes)
    return LoginResp(token=token)


@app.get("/tools")
def list_tools(user: UserCtx = Depends(get_user_ctx)):
    check_rate_limit(r, user.user_id)
    out = []
    for name, base in servers.items():
        data = requests.get(
            f"{base}/tools",
            timeout=TIMEOUT,
            headers={CORRELATION_HEADER: getattr(user, "correlation_id", "")},
        ).json()
        for t in data["tools"]:
            allowed = is_allowed(user, t["required_scope"])
            out.append({**t, "server": name, "allowed": allowed})
    return {"tools": out}


@app.post("/tools/call")
def call_tool(req: ToolCallReq, user: UserCtx = Depends(get_user_ctx)):
    check_rate_limit(r, user.user_id)
    cid = getattr(user, "correlation_id", "")

    if req.server not in servers:
        return JSONResponse(
            status_code=404,
            content=error_envelope(code="server_not_found", message="server_not_found", correlation_id=cid),
        )

    base = servers[req.server]
    tools = requests.get(
        f"{base}/tools",
        timeout=TIMEOUT,
        headers={CORRELATION_HEADER: getattr(user, "correlation_id", "")},
    ).json()["tools"]
    tool = next((t for t in tools if t["name"] == req.tool_name), None)
    if not tool:
        return JSONResponse(
            status_code=404,
            content=error_envelope(code="tool_not_found", message="tool_not_found", correlation_id=cid),
        )

    if not is_allowed(user, tool["required_scope"]):
        audit(
            r,
            {
                "type": "deny",
                "user": user.user_id,
                "role": user.role,
                "tool": req.tool_name,
                "server": req.server,
            },
        )
        return JSONResponse(
            status_code=403,
            content=error_envelope(code="forbidden_by_policy", message="forbidden_by_policy", correlation_id=cid),
        )

    audit(
        r,
        {
            "type": "allow",
            "user": user.user_id,
            "role": user.role,
            "tool": req.tool_name,
            "server": req.server,
        },
    )

    try:
        resp = requests.post(
            f"{base}/call",
            json=req.model_dump(),
            timeout=TIMEOUT,
            headers={CORRELATION_HEADER: getattr(user, "correlation_id", "")},
        )
    except requests.RequestException as e:
        return JSONResponse(
            status_code=502,
            content=error_envelope(code="upstream_down", message="mcp_server_unreachable", correlation_id=cid, detail=str(e)),
        )

    try:
        payload = resp.json()
    except Exception:
        return JSONResponse(
            status_code=502,
            content=error_envelope(code="bad_upstream_response", message="mcp_server_bad_json", correlation_id=cid, detail=resp.text),
        )

    # Normalize MCP-style responses into RESTful HTTP status codes while preserving envelope.
    # MCP servers may return:
    #  - {ok:true, ...}
    #  - {ok:false, error:{code,message,...}, ...}
    #  - {ok:false, error:"tool_not_found", ...}
    if isinstance(payload, dict) and payload.get("ok") is False:
        err = payload.get("error")
        code = None
        message = None
        detail = None
        if isinstance(err, dict):
            code = err.get("code") or "error"
            message = err.get("message") or code
            detail = err.get("detail")
        elif isinstance(err, str):
            code = err
            message = err

        # Map common error codes to HTTP status.
        status = 400
        if code in {"validation_error"}:
            status = 422
        elif code in {"forbidden_by_policy", "query_id_not_allowed", "task_not_allowed", "tool_not_allowed"}:
            status = 403
        elif code in {"tool_not_found", "server_not_found"}:
            status = 404
        elif code in {"mcp_timeout"}:
            status = 504
        elif code in {"task_error"}:
            status = 500

        # Ensure we always have our standard envelope fields.
        # Keep backward-compatible `detail` when present.
        normalized = error_envelope(
            code=code or "error",
            message=message or "error",
            correlation_id=payload.get("correlation_id") or cid,
            detail=detail,
        )
        normalized["detail"] = message or code or "error"
        return JSONResponse(status_code=status, content=normalized)

    return payload


def _looks_like_upstream_down(litellm_detail: object) -> bool:
    """Heuristic: LiteLLM may return HTTP 500/503 even when the *real* cause is upstream connection failure.

    We normalize those cases to 502 upstream_down to support the "deny vs upstream down" acceptance criteria.
    """
    try:
        s = json.dumps(litellm_detail, ensure_ascii=False)
    except Exception:
        s = str(litellm_detail)

    s_low = s.lower()
    # Common markers seen in LiteLLM/OpenAI adapter failures
    markers = [
        "connection error",
        "connection refused",
        "connecterror",
        "timed out",
        "timeout",
        "temporary failure",
        "name or service not known",
        "no route to host",
        "available model group",
        "model group",
        "upstream",
    ]
    return any(m in s_low for m in markers)


@app.post("/chat")
def chat(req: ChatReq, user: UserCtx = Depends(get_user_ctx), request: Request = None):
    check_rate_limit(r, user.user_id)

    # soft budget: chat is the main traffic sink
    cid = getattr(getattr(request, "state", object()), "correlation_id", "") or new_correlation_id()
    if not _consume_budget(r, user.user_id, n_chars=len(req.message)):
        raise HTTPException(429, error_envelope(code="budget_exceeded", message="daily_budget_exceeded", correlation_id=cid))

    mem_key = f"mem:{user.user_id}:{req.conversation_id}"
    history = r.lrange(mem_key, 0, 200)

    # Always store USER first (backward compatible with memory_size expectation)
    r.lpush(mem_key, f"USER: {req.message}")
    r.expire(mem_key, MEMORY_TTL)

    # === Profile memory guard (works without LLM) ===
    # Save: detect "我叫/我是/叫我 <name>" and persist into Redis.
    # Recall: detect "我叫什麼/我名字是什麼/我的名字" and answer directly.
    prof_key = f"memprof:{user.user_id}:{req.conversation_id}"
    msg = (req.message or "").strip()

    # --- helpers / guards ---
    BAD_NAMES = {"什麼", "誰", "哪個", "多少", "哪裡", "幾歲", "幾號", "幾點", "幾"}
    def _clean_name(s: str) -> str:
        return (s or "").strip().strip("，,。.!！?？:：；;\"'()（）[]【】<>《》 ")

    def _is_ask_name(text: str) -> bool:
        t = (text or "").strip()
        # 強力正規化：去掉所有空白字元（含全形/不可見）
        t2 = "".join(t.split()).replace("？", "?")
        return (
            ("我叫什麼" in t2) or ("我名字是什麼" in t2) or ("我的名字是什麼" in t2)
            or (("我叫" in t2) and ("什麼" in t2))  # 這條是保險：不管中間夾什麼不可見字元，都會命中
        )

    def _as_str(v):
        if v is None:
            return None
        return v.decode("utf-8", errors="ignore") if isinstance(v, (bytes, bytearray)) else str(v)

    # (1) Read path FIRST: avoid treating "我叫什麼" as "我叫 <name>" and overwriting profile.
    if _is_ask_name(msg):
        name = _as_str(r.hget(prof_key, "name"))
        if name:
            reply = f"你叫{name}。"
            r.lpush(mem_key, f"ASSISTANT: {reply}")
            audit(
                r,
                {
                    "type": "chat",
                    "user": user.user_id,
                    "role": user.role,
                    "conversation_id": req.conversation_id,
                    "mode": "mem_guard",
                    "action": "recall_name",
                    "hit": True,
                },
            )
            return {"reply": reply, "memory_size": len(history) + 2, "memory": {"hit": True, "name": name}}

        reply = "我還不知道你的名字。你可以跟我說「我叫XXX」。"
        r.lpush(mem_key, f"ASSISTANT: {reply}")
        audit(
            r,
            {
                "type": "chat",
                "user": user.user_id,
                "role": user.role,
                "conversation_id": req.conversation_id,
                "mode": "mem_guard",
                "action": "recall_name",
                "hit": False,
            },
        )
        return {"reply": reply, "memory_size": len(history) + 2, "memory": {"hit": False}}

    # (2) Write path: only save if extracted name looks valid (not a question word).
    for p in NAME_PATTERNS:
        t2 = "".join(msg.split()).replace("？", "?")
        if ("我叫" in t2) and ("什麼" in t2):
            m = None
        m = p.search(msg)
        if not m:
            continue

        name = _clean_name(m.group("name"))

        # Reject ambiguous / question words
        if (not name) or (name in BAD_NAMES) or ("什麼" in name) or ("誰" in name):
            continue

        r.hset(prof_key, mapping={"name": name})
        r.expire(prof_key, MEMORY_TTL)

        reply = f"收到，我記住了：你叫{name}。"
        r.lpush(mem_key, f"ASSISTANT: {reply}")
        audit(
            r,
            {
                "type": "chat",
                "user": user.user_id,
                "role": user.role,
                "conversation_id": req.conversation_id,
                "mode": "mem_guard",
                "action": "save_name",
            },
        )
        return {"reply": reply, "memory_size": len(history) + 2, "memory": {"saved": True, "name": name}}

    # Cold-start / state mgmt: summarize if history grows too large.
    # Keep last MEMORY_MAX_TURNS lines, summarize the rest into memsum:*.
    if len(history) > MEMORY_MAX_TURNS:
        # Summarize older turns (best-effort; never block request if summarization fails)
        older = list(reversed(history[MEMORY_MAX_TURNS:]))
        summary_key = f"memsum:{user.user_id}:{req.conversation_id}"
        try:
            # Use the same chosen model later; if no model, skip
            chosen_for_summary = (req.model or DEFAULT_MODEL)
            if chosen_for_summary:
                role_keys = _load_role_keys()
                vkey = role_keys.get(user.role)
                if vkey:
                    summary_prompt = "Summarize the conversation briefly in Traditional Chinese."
                    summary_text = _litellm_chat_completion(
                        virtual_key=vkey,
                        model=chosen_for_summary,
                        message=summary_prompt + "\n\n" + "\n".join(older[-60:]),
                        history=[],
                    )
                    r.setex(summary_key, MEMORY_TTL, summary_text)
                    # Trim list to keep it bounded
                    r.ltrim(mem_key, 0, MEMORY_MAX_TURNS - 1)
        except Exception:
            pass

    # Decide model
    chosen_model = (req.model or DEFAULT_MODEL)

    # If no model provided & no default, keep old behavior (demo)
    if not chosen_model:
        reply = f"(demo) hi {user.user_id}({user.role}), you said: {req.message}"
        r.lpush(mem_key, f"ASSISTANT: {reply}")
        audit(r, {"type": "chat", "user": user.user_id, "role": user.role, "conversation_id": req.conversation_id, "mode": "demo"})
        return {"reply": reply, "memory_size": len(history) + 2}

    # Role -> LiteLLM virtual key
    role_keys = _load_role_keys()
    vkey = role_keys.get(user.role)
    if not vkey:
        # Misconfiguration, not policy.
        raise HTTPException(500, "litellm_virtual_key_missing")

    try:
        reply = _litellm_chat_completion(virtual_key=vkey, model=chosen_model, message=req.message, history=history)
    except HTTPException as e:
        # Normalize LiteLLM "upstream connection" failures (often surfaced as 500) into 502 upstream_down.
        detail = e.detail if isinstance(e.detail, dict) else {"detail": e.detail}
        litellm_blob = detail.get("litellm", detail)

        if e.status_code in {500, 502, 503, 504} and _looks_like_upstream_down(litellm_blob):
            env = error_envelope(
                code="upstream_down",
                message="litellm_upstream_unreachable",
                correlation_id=cid,
                detail=litellm_blob,
            )
            return JSONResponse(status_code=502, content=env, headers={BLOCKED_HEADER_NAME: BLOCKED_HEADER_VALUE})

        # Otherwise treat as policy/model allowlist/validation error from LiteLLM.
        detail.setdefault("blocked_by", "litellm")
        return JSONResponse(status_code=e.status_code, content={"detail": detail}, headers={BLOCKED_HEADER_NAME: BLOCKED_HEADER_VALUE})
    except requests.RequestException as e:
        # Upstream down / timeout
        env = error_envelope(code="upstream_down", message="litellm_unreachable", correlation_id=cid, detail=str(e))
        return JSONResponse(status_code=502, content=env, headers={BLOCKED_HEADER_NAME: BLOCKED_HEADER_VALUE})

    r.lpush(mem_key, f"ASSISTANT: {reply}")

    audit(
        r,
        {
            "type": "chat",
            "user": user.user_id,
            "role": user.role,
            "conversation_id": req.conversation_id,
            "mode": "litellm",
            "model": chosen_model,
        },
    )

    return {"reply": reply, "memory_size": len(history) + 2}


@app.get("/v1/agent/tools")
def agent_tools(user: UserCtx = Depends(get_user_ctx), request: Request = None):
    """Return the *agent-visible* tool list for this JWT role (visibility matrix)."""
    check_rate_limit(r, user.user_id)
    cid = getattr(request.state, "correlation_id", new_correlation_id())
    visibility = load_agent_visibility(user.role, "/app/configs/agent_permissions.yaml")

    all_tools: List[ToolSpec] = []
    for name, base in servers.items():
        data = requests.get(f"{base}/tools", timeout=TIMEOUT, headers={CORRELATION_HEADER: cid}).json()
        for t in data.get("tools", []):
            all_tools.append(
                ToolSpec(server=name, name=t["name"], required_scope=t["required_scope"], description=t.get("description", ""))
            )
    visible = filter_tools_for_role(all_tools, visibility)
    return {
        "ok": True,
        "role": user.role,
        "visibility": visibility,
        "tools": [
            {"full_name": t.full_name, "server": t.server, "name": t.name, "required_scope": t.required_scope, "description": t.description}
            for t in visible
        ],
    }


@app.post("/v1/agent/run")
def agent_run(req: AgentRunReq, user: UserCtx = Depends(get_user_ctx), request: Request = None):
    """LangGraph agent runner.

    - Tool visibility is determined by agent_permissions.yaml (role-based).
    - Tool invocation ALWAYS goes through `/tools/call` (Gateway final defense).
    """
    check_rate_limit(r, user.user_id)
    cid = getattr(request.state, "correlation_id", new_correlation_id())

    # --- budgets / guards ---
    if not _consume_budget(r, user.user_id, n_chars=len(req.message) * 2):
        raise HTTPException(
            429,
            error_envelope(code="budget_exceeded", message="daily_budget_exceeded", correlation_id=cid),
        )

    if LG_AGENT is None:
        raise HTTPException(
            500,
            error_envelope(code="agent_unavailable", message="langgraph_not_ready", correlation_id=cid),
        )

    # --- resolve model + litellm base ---
    chosen_model = (req.model or DEFAULT_MODEL)
    if not chosen_model:
        # Keep consistent with /chat demo-mode
        return {
            "ok": True,
            "reply": f"(demo-agent) hi {user.user_id}({user.role}), you said: {req.message}",
            "correlation_id": cid,
        }

    litellm_base_url = os.getenv("LITELLM_BASE_URL", "http://litellm:4000")

    # --- resolve virtual key (role-based) ---
    role_keys = _load_role_keys()
    vkey = role_keys.get(user.role)
    if not vkey:
        raise HTTPException(
            500,
            error_envelope(code="misconfig", message="litellm_virtual_key_missing", correlation_id=cid),
        )

    # --- tool visibility (role-based) ---
    visibility = load_agent_visibility(user.role, "/app/configs/agent_permissions.yaml")

    # --- discover MCP tools (best-effort; skip failed servers) ---
    all_tools: List[ToolSpec] = []
    for name, base in servers.items():
        try:
            resp = requests.get(
                f"{base}/tools",
                timeout=TIMEOUT,
                headers={CORRELATION_HEADER: cid},
            )
            resp.raise_for_status()
            data = resp.json()
        except Exception as e:
            # 失敗就把該 server 略過，避免整個 agent/run 500
            audit(
                r,
                {
                    "type": "agent",
                    "user": user.user_id,
                    "role": user.role,
                    "conversation_id": req.conversation_id,
                    "mode": "agent_run",
                    "action": "discover_tools_failed",
                    "server": name,
                    "error": str(e),
                    "correlation_id": cid,
                },
            )
            continue

        for t in data.get("tools", []):
            all_tools.append(
                ToolSpec(
                    server=name,
                    name=t["name"],
                    required_scope=t["required_scope"],
                    description=t.get("description", ""),
                )
            )

    visible = filter_tools_for_role(all_tools, visibility)
    visible_tools = [
        {
            "full_name": t.full_name,
            "server": t.server,
            "tool_name": t.name,
            "required_scope": t.required_scope,
            "description": t.description,
        }
        for t in visible
    ]

    # --- tool invocation wrapper (ALWAYS through /tools/call) ---
    def call_tools_fn(*, server: str, tool_name: str, args: dict):
        # Invocation guard 1: visibility
        full_name = f"{server}.{tool_name}"
        if not any(_matches(p, full_name) for p in visibility):
            return error_envelope(
                code="tool_not_visible",
                message="tool_not_visible_for_role",
                correlation_id=cid,
                detail={"tool": full_name},
            )

        # Invocation guard 2: defer to existing endpoint (final defense includes RBAC scopes)
        try:
            return call_tool(ToolCallReq(server=server, tool_name=tool_name, args=args), user)
        except HTTPException as e:
            # Normalize deny vs upstream-down
            if e.status_code == 403:
                return error_envelope(code="policy_deny", message="forbidden_by_policy", correlation_id=cid)
            return (
                e.detail
                if isinstance(e.detail, dict)
                else error_envelope(code="tool_error", message="tool_call_failed", correlation_id=cid, detail=e.detail)
            )

    # --- Execute LangGraph ---
    # IMPORTANT:
    # - These keys MUST exist because plan() reads them:
    #   litellm_base_url, virtual_key, model, user_message, visible_tools, timeout_s
    # - If you want to pass call_tools_fn through state, add it into AgentState TypedDict.
    state = {
        "user_message": req.message,
        "conversation_id": req.conversation_id,
        "model": chosen_model,
        "correlation_id": cid,
        "visible_tools": visible_tools,
        "litellm_base_url": litellm_base_url,
        "virtual_key": vkey,
        "timeout_s": TIMEOUT,

        # Optional: only if AgentState includes it (otherwise LangGraph may drop it)
        "call_tools_fn": call_tools_fn,
    }

    out = LG_AGENT.invoke(state)
    reply = (out.get("final") or {}).get("reply") or ""

    # Persist a lightweight trace (for debugging / cold-start)
    trace_key = f"trace:{cid}"
    r.setex(
        trace_key,
        60 * 60,
        json.dumps(
            {
                "role": user.role,
                "tools": visible_tools,
                "action": out.get("action"),
                "tool_result": out.get("tool_result"),
            },
            ensure_ascii=False,
        ),
    )

    return {
        "ok": True,
        "reply": reply,
        "correlation_id": cid,
        "agent": {
            "action": out.get("action"),
            "tool_result": out.get("tool_result"),
        },
    }